# This file generated by Quarto; do not edit by hand.
# shiny_mode: core

from __future__ import annotations

from pathlib import Path
from shiny import App, Inputs, Outputs, Session, ui

import pandas as pd
import plotly.express as px
from shiny.express import input, ui
from shinywidgets import render_widget  

f = './Temixco_2018_10Min.csv'

tmx = pd.read_csv(f,index_col=0,parse_dates=True)
columnas = tmx.columns.to_list()

# ========================================================================




def server(input: Inputs, output: Outputs, session: Session) -> None:
    ui.input_selectize(  
        "variable",  
        "Selecciona:", 
        columnas,
        multiple=True,
    )  

    # ========================================================================

    @render_widget  
    def plot():  
        scatterplot = px.line(
            data_frame=tmx,
            x=tmx.index,
            y=list(input.variable())
        )
        return scatterplot  

    # ========================================================================



    return None


_static_assets = ["index_files","Temixco_2018_10Min.csv","index_files/libs/quarto-html/tippy.css","index_files/libs/quarto-html/quarto-syntax-highlighting-e26003cea8cd680ca0c55a263523d882.css","index_files/libs/bootstrap/bootstrap-icons.css","index_files/libs/bootstrap/bootstrap-d16340f909bcc4c0fb2c16a39b3d3bba.min.css","index_files/libs/quarto-dashboard/datatables.min.css","index_files/libs/clipboard/clipboard.min.js","index_files/libs/quarto-html/quarto.js","index_files/libs/quarto-html/popper.min.js","index_files/libs/quarto-html/tippy.umd.min.js","index_files/libs/quarto-html/anchor.min.js","index_files/libs/bootstrap/bootstrap.min.js","index_files/libs/quarto-dashboard/quarto-dashboard.js","index_files/libs/quarto-dashboard/stickythead.js","index_files/libs/quarto-dashboard/datatables.min.js","index_files/libs/quarto-dashboard/pdfmake.min.js","index_files/libs/quarto-dashboard/vfs_fonts.js","index_files/libs/quarto-dashboard/web-components.js","index_files/libs/quarto-dashboard/components.js"]
_static_assets = {"/" + sa: Path(__file__).parent / sa for sa in _static_assets}

app = App(
    Path(__file__).parent / "index.html",
    server,
    static_assets=_static_assets,
)
