# This file generated by Quarto; do not edit by hand.
# shiny_mode: core

from __future__ import annotations

from pathlib import Path
from shiny import App, Inputs, Outputs, Session, ui




def server(input: Inputs, output: Outputs, session: Session) -> None:
    from shiny.express import input, render, ui

    ui.input_slider("val", "Slider label", min=0, max=100, value=50)

    @render.text
    def slider_val():
        return f"Slider value: {input.val()}"

    # ========================================================================



    return None


_static_assets = ["index_files","index_files\\libs\\quarto-html\\tippy.css","index_files\\libs\\quarto-html\\quarto-syntax-highlighting-2486e1f0a3ee9ee1fc393803a1361cdb.css","index_files\\libs\\bootstrap\\bootstrap-icons.css","index_files\\libs\\bootstrap\\bootstrap-a9602187df57603a0604ee5b90d4421e.min.css","index_files\\libs\\quarto-dashboard\\datatables.min.css","index_files\\libs\\clipboard\\clipboard.min.js","index_files\\libs\\quarto-html\\quarto.js","index_files\\libs\\quarto-html\\popper.min.js","index_files\\libs\\quarto-html\\tippy.umd.min.js","index_files\\libs\\quarto-html\\anchor.min.js","index_files\\libs\\bootstrap\\bootstrap.min.js","index_files\\libs\\quarto-dashboard\\quarto-dashboard.js","index_files\\libs\\quarto-dashboard\\stickythead.js","index_files\\libs\\quarto-dashboard\\datatables.min.js","index_files\\libs\\quarto-dashboard\\pdfmake.min.js","index_files\\libs\\quarto-dashboard\\vfs_fonts.js","index_files\\libs\\quarto-dashboard\\web-components.js","index_files\\libs\\quarto-dashboard\\components.js"]
_static_assets = {"/" + sa: Path(__file__).parent / sa for sa in _static_assets}

app = App(
    Path(__file__).parent / "index.html",
    server,
    static_assets=_static_assets,
)
